---
- name: Start DuckDNS and other server containers
  hosts: localhost

  vars:   
    duckdns_token: "{{ lookup('community.general.onepassword', 'op://Personal/o7lf4lazzfjnuxgc56sbyke5b4/token') }}"

  tasks:
    - name: Deploy DuckDNS
      community.docker.docker_compose_v2:
        project_src: /home/{{ ansible_user_id }}/Repos/nobara-setup/templates/docker/duckdns
        state: present
        environment:
          DUCKDNS_TOKEN: "{{ duckdns_token }}"

    # TODO: use proper container registry
    - name: Clone da-band
      ansible.builtin.git:
        repo: https://github.com/davay/da-band.git
        dest: /home/{{ ansible_user_id }}/Repos
        depth: 1

    - name: Deploy da-band API server
      ansible.builtin.shell:
        cmd: ./start.sh
        chdir: /home/{{ ansible_user_id }}/Repos/da-band/api/
