---
- name: Start DuckDNS and other server containers
  hosts: localhost

  vars: 
    user: "{{ ansible_user_id }}"
    base_dir: "/home/{{ user }}/Repos"
    duckdns_token: "{{ lookup('community.general.onepassword', 'duckdns token', field='token', vault='Personal') }}"
    soft_serve_initial_admin_keys: "{{ lookup('community.general.onepassword', 'Git', field='public key', vault='Personal') }}"

  tasks:
    - name: Ensure docker service is running
      systemd:
        name: docker
        state: started
        enabled: yes
      become: true

    - name: Create DuckDNS .env file
      template:
        src: "{{ base_dir }}/nobara-setup/templates/docker/duckdns/.env.j2"
        dest: "{{ base_dir }}/nobara-setup/templates/docker/duckdns/.env"

    - name: Deploy DuckDNS
      community.docker.docker_compose_v2:
        project_src: "{{ base_dir }}/nobara-setup/templates/docker/duckdns"
        state: present
      become: true
    
    - name: Create Soft-Serve .env file
      template:
        src: "{{ base_dir }}/nobara-setup/templates/docker/soft-serve/.env.j2"
        dest: "{{ base_dir }}/nobara-setup/templates/docker/soft-serve/.env"

    - name: Create Soft-Serve directory
      file:
        path: "/opt/soft-serve"
        state: directory
        mode: '0755'
      become: true

    - name: Copy Soft-Serve config
      template:
        src: "{{ base_dir }}/nobara-setup/templates/docker/soft-serve/config.yaml.j2"
        dest: "/opt/soft-serve/config.yaml"
      become: true

    - name: Deploy Soft-Serve
      community.docker.docker_compose_v2:
        project_src: "{{ base_dir }}/nobara-setup/templates/docker/soft-serve"
        state: present
      become: true

    # TODO: use proper container registry
    - name: Clone da-band
      ansible.builtin.git:
        version: main
        repo: https://github.com/davay/da-band.git
        dest: "{{ base_dir }}/da-band"
        depth: 1
        update: yes 
        force: yes

    - name: Deploy da-band API server
      ansible.builtin.shell:
        cmd: ./start.sh
        chdir: "{{ base_dir }}/da-band/api/"
      become: true
