- name: Copy dotfiles
  hosts: localhost
  become: true
  tasks:
  - name: Copy root dotfiles
    ansible.builtin.get_url:
      url: "https://raw.githubusercontent.com/davay/dotfiles/main/{{ item }}"
      dest: "~/{{ item | basename }}"
    loop:
      - .zshrc
      - .zshrc_portable
      - .p10k.zsh
