- name: Copy dotfiles
  hosts: localhost
  tasks:
  - name: Copy dotfiles
    ansible.builtin.get_url:
      url: "https://raw.githubusercontent.com/davay/dotfiles/main/{{ item }}"
      dest: "/home/{{ ansible_user_id }}/{{ item }}"
    loop:
      - .zshrc
      - .zshrc_portable
      - .p10k.zsh
      - .gitconfig
      - .gitconfig_mac
      - .gitconfig_linux
      - .ssh/config
      - .config/1Password/ssh/agent.toml
