- name: Copy dotfiles
  hosts: localhost
  tasks:
  - name: Copy root dotfiles
    ansible.builtin.get_url:
      url: "https://raw.githubusercontent.com/davay/dotfiles/main/{{ item }}"
      dest: "/home/{{ ansible_user_id }}/{{ item | basename }}"
    loop:
      - .zshrc
      - .zshrc_portable
      - .p10k.zsh
      - .gitconfig
