- name: Copy dotfiles
  hosts: localhost
  vars: 
    dotfiles:
      - .zshrc
      - .zshrc_portable
      - .p10k.zsh
      - .gitconfig
      - .gitconfig_mac
      - .gitconfig_linux
      - .ssh/config
      - .config/1Password/ssh/agent.toml

  tasks:
  - name: Create directories
    ansible.builtin.file:
      path: "/home/{{ ansible_user_id }}/{{ item | dirname }}"
      state: directory
    loop: "{{ dotfiles }}"
    when: "'/' in item"

  - name: Copy dotfiles
    ansible.builtin.get_url:
      url: "https://raw.githubusercontent.com/davay/dotfiles/main/{{ item }}"
      dest: "/home/{{ ansible_user_id }}/{{ item }}"
      force: true
    loop: "{{ dotfiles }}"
