---
- name: Setup FirewallD
  hosts: localhost
  become: true
  tasks: 
    - name: Allow HTTP traffic
      ansible.posix.firewalld:
        service: http
        zone: public
        permanent: yes
        state: enabled
        immediate: true
    
    - name: Allow HTTPS traffic
      ansible.posix.firewalld:
        service: https
        zone: public
        permanent: yes
        state: enabled
        immediate: true

    - name: Allow Docker FastAPI (da-band)
      ansible.posix.firewalld:
        port: 8000/tcp
        zone: public
        permanent: yes
        state: enabled
        immediate: true

    - name: Allow KDE Connect
      ansible.posix.firewalld:
        service: kdeconnect
        zone: public
        permanent: yes
        state: enabled 
        immediate: true
    
    - name: Allow MOSH traffic
      ansible.posix.firewalld:
        port: 60000-61000/udp
        zone: public
        permanent: yes
        state: enabled
        immediate: true

    - name: Allow Soft-Serve (git) traffic
      ansible.posix.firewalld:
        port: "{{ item }}/tcp"
        zone: public
        permanent: yes
        state: enabled
        immediate: true
      loop:
        - 23231
        - 23232
        - 23233
        - 9418

