---
- name: Initialize system
  hosts: localhost
  vars:
    installed_gnome_extensions: "{{ lookup('pipe', 'gext list') }}"
    fedora_version: "{{ lookup('pipe', 'rpm -E %fedora') }}"
  tasks:
    - name: "Enable Fedora COPRs (chroot: fedora-{{ fedora_version }}-x86_64)"
      community.general.copr:
        name: "{{ item }}"
        chroot: "fedora-{{ fedora_version }}-x86_64"
        state: enabled
      loop: 
          - pgdev/ghostty
          - sneexy/zen-browser
      become: true

    - name: Import 1Password GPG key
      ansible.builtin.rpm_key:
        key: https://downloads.1password.com/linux/keys/1password.asc
        state: present
      become: true

    - name: Add repositories
      ansible.builtin.yum_repository:
        name: "{{ item.name }}"
        description: "{{ item.description }}"
        baseurl: "{{ item.baseurl }}"
        enabled: true
        gpgcheck: "{{ item.gpgcheck | default(true) }}"
        gpgkey: "{{ item.gpgkey | default(omit) }}"
      loop:
        - name: 1password
          description: 1Password Repository
          baseurl: https://downloads.1password.com/linux/rpm/stable/$basearch
          gpgkey: https://downloads.1password.com/linux/keys/1password.asc
        - name: nvidia-container-toolkit
          description: NVIDIA Container Toolkit Repository
          baseurl: https://nvidia.github.io/libnvidia-container/stable/rpm/$basearch
          gpgkey: https://nvidia.github.io/libnvidia-container/gpgkey
      become: true
    
    - name: Install DNF packages
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      loop: 
        - ghostty
        - neovim
        - zsh
        - zen-browser
        - lsd
        - python3
        - python3-pip
        - 1password
        - git-credential-libsecret
        - gh
        - nvidia-container-toolkit
        - docker
      become: true

    - name: Install Oh-My-Zsh
      ansible.builtin.git:
        repo: https://github.com/ohmyzsh/ohmyzsh.git
        dest: /home/{{ ansible_user_id }}/.oh-my-zsh
        depth: 1

    - name: Install Powerlevel10k
      git: 
        repo: https://github.com/romkatv/powerlevel10k.git
        dest: /home/{{ ansible_user_id }}/powerlevel10k
        depth: 1

    - name: Change user shell to Zsh 
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        shell: /bin/zsh
      become: true

    - name: Install gnome-extensions-cli
      ansible.builtin.pip:
        name: gnome-extensions-cli
        extra_args: --user --upgrade
        
    - name: Install GNOME extensions
      ansible.builtin.command:
        cmd: gext --filesystem install "{{ item }}"
      loop:
        - paperwm@paperwm.github.com
        - gsconnect@andyholmes.github.io
      changed_when: item not in installed_gnome_extensions

    - name: Swap Caps Lock and Escape
      community.general.dconf:
        key: "/org/gnome/desktop/input-sources/xkb-options"
        value: "['caps:escape']"
        state: present

  post_tasks: 
    - name: Verify NVIDIA Container Toolkit installation
      ansible.builtin.command:
        cmd: docker run --rm --gpus all nvidia/cuda:latest-cudnn-runtime nvidia-smi
      register: nvidia_test
      changed_when: false
      become: true

    - name: Display final message
      vars:
        msg: |
             ===========================================

             For GNOME extension changes to take effect,
             please log out and log back in

             NVIDIA Container Toolkit test results:
             {{ nvidia_test.stdout if nvidia_test.stdout is defined else 'Test failed' }}

             ===========================================
      debug:
        msg: "{{ msg.split('\n') }}"
