---
- name: Initialize system
  hosts: localhost
  tasks:
    - name: Get Fedora version
      command: rpm -E %fedora
      register: fedora_version
      changed_when: false
    
    - name: "Enable Fedora COPRs (chroot: fedora-{{ fedora_version.stdout }}-x86_64)"
      community.general.copr:
        name: "{{ item }}"
        chroot: "fedora-{{ fedora_version.stdout }}-x86_64"
        state: enabled
      loop: 
          - pgdev/ghostty
          - sneexy/zen-browser
      become: true
    
    - name: Install DNF packages
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      loop: 
        - ghostty
        - neovim
        - zsh
        - zen-browser
        - lsd
      become: true

    - name: Install Oh-My-Zsh
      ansible.builtin.git:
        repo: https://github.com/ohmyzsh/ohmyzsh.git
        dest: /home/{{ ansible_user_id }}/.oh-my-zsh
        depth: 1

    - name: Install Powerlevel10k
      git: 
        repo: https://github.com/romkatv/powerlevel10k.git
        dest: /home/{{ ansible_user_id }}/powerlevel10k
        depth: 1

    - name: Change user shell to Zsh 
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        shell: /bin/zsh
      become: true
