---
- name: Initialize system
  hosts: localhost
  become: true
  tasks:
    - name: Get Fedora version
      command: rpm -E %fedora
      register: fedora_version
      changed_when: false
    
    - name: "Enable Fedora COPRs (chroot: fedora-{{ fedora_version.stdout }}-x86_64)"
      community.general.copr:
        name: pgdev/ghostty
        chroot: "fedora-{{ fedora_version.stdout }}-x86_64"
    
    - name: Install Ghostty
      ansible.builtin.dnf:
        name: ghostty
        state: present

    - name: Install Neovim
      ansible.builtin.dnf:
        name: neovim
        state: present

    - name: Install Zsh
      ansible.builtin.dnf:
        name: zsh
        state: present

    - name: Install Oh My Zsh
      ansible.builtin.git:
      repo: https://github.com/ohmyzsh/ohmyzsh.git
      dest: ~/.oh-my-zsh
      depth: 1

    - name: Install Powerlevel10k
      git: 
        repo: https://github.com/romkatv/powerlevel10k.git
        dest: ~/powerlevel10k
        depth: 1
