---
- name: Setup NGINX
  hosts: localhost
  vars:
    user: "{{ ansible_user_id }}"
    domains:
      - api.devinl.im
      - git.devinl.im
    email: davay@devinl.im
  tasks: 
    - name: Install NGINX and Certbot
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      loop:
        - nginx
        - certbot
        - python3-certbot-nginx
      become: true
    
    - name: Copy nginx.conf
      ansible.builtin.template: 
        src: /home/{{ user }}/Repos/nobara-setup/templates/nginx.conf
        dest: /etc/nginx/nginx.conf
      become: true
    
    - name: Check if certificates exist
      ansible.builtin.stat:
        path: "/etc/letsencrypt/live/{{ item }}/fullchain.pem"
      register: cert_exists
      loop: "{{ domains }}"
      become: true

    - name: Enable and start NGINX service
      ansible.builtin.systemd:
        name: nginx
        enabled: yes
        state: started
      become: true

    - name: Obtain SSL cert for domains
      ansible.builtin.command: 
        cmd: > 
          certbot --nginx 
          {% for domain in domains %}-d {{ domain }} {% endfor %}
          --non-interactive --agree-tos 
          --email {{ email }}
          --redirect
          --expand
      become: true
      when: cert_exists.results | map(attribute='stat.exists') | select | list | length < domains | length
