---
- name: Setup NGINX
  hosts: localhost
  vars:
    user: "{{ ansible_user_id }}"
    domain: api.devinl.im
    email: davay@devinl.im
  tasks: 
    - name: Install NGINX and Certbot
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      loop:
        - nginx
        - certbot
        - python3-certbot-nginx
      become: true
    
    - name: Copy nginx.conf
      template: 
        src: /home/{{ user }}/Repos/nobara-setup/templates/nginx.conf
        dest: /etc/nginx/nginx.conf
      become: true
    
    - name: Enable and start NGINX service
      systemd:
        name: nginx
        enabled: yes
        state: started
      become: true

    - name: "Obtain SSL cert for {{ domain }}"
      command: > 
        certbot --nginx -d {{ domain }} 
        --non-interactive --agree-tos 
        --email {{ email }}
        --redirect
      become: true
      creates: /etc/letsencrypt/live/{{ domain }}/fullchain.pem
