---
- name: Setup NGINX
  hosts: localhost
  vars:
    domain: api.devinl.im
    email: davay@devinl.im
  tasks: 
    - name: Install NGINX and Certbot
      ansible.builtin.dnf:
        name: 
          - nginx
          - certbot
          - python3-certbot-nginx
        state: present
    
    - name: Copy nginx.conf
      template: 
        src: ~/Repos/nobara-setup/templates/nginx.conf
        dest: /etc/nginx/nginx.conf
    
    - name: Enable and start NGINX service
      systemd:
        name: nginx
        enabled: yes
        state: started

    - name: Obtain SSL cert
      command: > 
        certbot --nginx -d {{ domain }} 
        --non-interactive --agree-tos 
        --email {{ email }}

    - name: Reload NGINX service to apply SSL changes
      systemd:
        name: nginx
        state: reloaded
