---
- name: Configure SSH server
  hosts: localhost
  become: true
  tasks:
    - name: Configure SSH daemon to use port 2222
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?Port'
        line: 'Port 2222'
        backup: yes
      notify: restart sshd

    - name: Ensure SSH service is enabled and started
      ansible.builtin.systemd:
        name: sshd
        state: started
        enabled: yes

  handlers:
    - name: restart sshd
      ansible.builtin.systemd:
        name: sshd
        state: restarted